name: Dofutils CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  code-sanitize:
    name: Code Sanitize
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true

      - name: Check code sanitize
        run: |
          uv sync --all-groups
          uv run ruff check .
          uv run ruff format --check .
          uv run mypy . --exclude '^tests/'

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run unittests
        run: uv run task test
